services:
  # Backend service
  - type: web
    name: lip-reading-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: USE_DUMMY_MODEL
        value: false
      - key: HF_REPO_ID
        value: AnuragShirke/lip-reading-models

  # Frontend service
  - type: web
    name: lip-reading-frontend
    env: node
    buildCommand: cd frontend && npm install --production=false && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: BACKEND_URL
        value: https://lip-reading-backend.onrender.com
      - key: NODE_ENV
        value: production
